services:
  mysql:
    image: mysql:8.0
    container_name: ventas-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${DB_NAME:-ventas_db}
      MYSQL_USER: ${DB_USER:-ventas_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-ventas_password}
    ports:
      - "${HOST_DB_PORT:-3307}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ventas-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  api-ventas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-ventas
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src:cached
      - ./tsconfig.json:/app/tsconfig.json:cached
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ventas-network
volumes:
  mysql_data:
    driver: local
networks:
  ventas-network:
    driver: bridge